#!/bin/bash

image_tag="latest"

if $1; then
    image_tag=$1
fi

print $image_tag

docker_compose_destinations='docker-compose -f ../bills/docker-compose.yml -f ../weight/docker-compose.yml -f ./docker-compose.override.yml'

$docker_compose_destinations up -d

./sanity.py
