#!/bin/bash

set -e

# service directories
base_dir_path=".."

if (( $# > 1 )); then
    base_dir_path=$2
fi

weight_path="weight"
bills_path="bills"
devops_path="devops"
docker_compose_destinations='-f '$base_dir_path'/'$bills_path'/docker-compose.yml -f '$base_dir_path'/'$weight_path'/docker-compose.yml -f '$base_dir_path'/'$devops_path'/docker-compose.override.yml'

image_tag="latest"
if [ $# -ne 0 ]; then
    image_tag=$1
fi

build_img_by_path ()
{
    path=$1
    tag=$2

    docker build -f $base_dir_path/$path/Dockerfile --tag $path:$tag $base_dir_path/$path

    return $?
}


echo "Tagging images with version $image_tag"

build_img_by_path $weight_path/app $image_tag
build_img_by_path $bills_path/app $image_tag

docker-compose $docker_compose_destinations up -d

python3 -m pip install --user pytest

python3 -m pytest $base_dir_path/$devops_path/test_sanity.py

python3 -m pip uninstall --yes pytest

docker-compose $docker_compose_destinations down
